database:
  image: mysql
  volumes:
    - ./db-dump:/docker-entrypoint-initdb.d
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "ttc_bus_data"
    MYSQL_USER: "test"
    MYSQL_PASSWORD: "test"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"